require("nvim-treesitter.configs").setup({
	ensure_installed = {
		"vim",
		"lua",
		"vimdoc",
		"bash",
		"comment",
		"ssh_config",
		"git_config",
		"git_rebase",
		"gitattributes",
		"gitcommit",
		"gitignore",
		"markdown",
		"markdown_inline",
		"html",
		"css",
		"scss",
		"javascript",
		"tsx",
		"typescript",
		"json",
		"sql",
		"regex",
	},
	sync_install = false,
	auto_install = true,
	autotag = {
		enable = true,
	},
	fold = { enable = true },
	highlight = {
		enable = true,
		additional_vim_regex_highlighting = true,
	},
})
